# Generated by Django 3.1 on 2020-09-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
