# Generated by Django 3.1 on 2020-09-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_eventmember_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
